services:
  backend:
    build: .
    container_name: sescam-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/hospital?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8080:8080"

  frontend:
    build: ./Frontend
    container_name: sescam-web
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"